name: 'deploy'

on:
  push:
    branches: [ "main" ]

jobs:    
  docker:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker Build
        run: |
              docker build -t ${{ secrets.DOCKER_REPO }}:front .
      
      - name: push
        run: |
              docker push ${{ secrets.DOCKER_REPO }}:front